### ISSUE TITLE
Uncaught exception/noclassdeffounderror?

### ISSUE THREAD

**Issue by LemmaEOF** [CharsetMC/CharsetPatches#1]
CharsetPatches version 0.1.1, 0.5.0.124, forge 1.12.2-14.23.1.2584

With charsetpatches in, the game window never has time to even appear before the game crashes. It starts the launch process then stops.  [Here's](https://pastebin.com/ZJTq3m3g) a log of the launch sequence. There seems to be a `[java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: net/minecraftforge/common/config/Configuration` but I have no idea what that's coming from.

**Comment by ChloeDawn** [comment]
It is possible that those classes may not be present at that time. Really you shouldn't be class loading in a transformer at all...

**Comment by asiekierka** [comment]
>This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**Comment by asiekierka** [comment]
@InsomniaKitten FoamFix has been using the Configuration classes like this for a long time now without any issues. I'm not sure why this happens with CharsetPatches.

**Comment by asiekierka** [comment]
[10:54:24] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:667]: Caused by: java.lang.NoClassDefFoundError: pl/asie/charset/patchwork/CharsetPatchwork

This is the actual problem.
